force-app/main/default/objects/TSS_Google_Map_Setting__mdt/TSS_Google_Map_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for Google Maps open source utility from TruSummit Solutions</description>
    <label>TSS Google Map Setting</label>
    <pluralLabel>TSS Google Map Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TSS_Google_Map_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>Your Google Maps API key which is required on every request.</description>
    <label>API Key</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TSS_Google_Map_Setting__mdt/fields/Google_Maps_API_Root__c.field-meta.xml
<CustomField>
    <fullName>Google_Maps_API_Root__c</fullName>
    <description>The Google Maps API Root URL</description>
    <label>Google Maps API Root</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TSSGoogleMapsAPIConnect.cls
public with sharing class TSSGoogleMapsAPIConnect {

    private static Map<String, String> GOOGLE_MAPS_DETAILS;

    public static void getGoogleMapsDetails() {
        List<TSS_Google_Map_Setting__mdt> googleMapsDetails = [SELECT Id, DeveloperName, Google_Maps_API_Root__c, API_Key__c
            FROM TSS_Google_Map_Setting__mdt WHERE DeveloperName = 'Google_Maps'];

        if (googleMapsDetails.isEmpty()) {
            throw new TSSGoogleMaps.GoogleMapsException('Google Maps custom metadata type with developername Google_Maps not found!');
        }

        TSS_Google_Map_Setting__mdt googleMapsDetail = googleMapsDetails.get(0);

        GOOGLE_MAPS_DETAILS = new Map<String, String> {
            'rootUrl' => googleMapsDetail.Google_Maps_API_Root__c,
            'apiKey' => googleMapsDetail.API_Key__c
        };
    }

    private static void initSettings() {
        if (GOOGLE_MAPS_DETAILS == null) {
            getGoogleMapsDetails();
        }
    }

    /**
     * This method should be implemented to adhere to your security requirements. In this example,
     * the key is being returned as a result of querying a Custom Metadata Type.
     *
     * @return A String representing the Google Maps API key
     */
    public static String getKey() {
        initSettings();
        return GOOGLE_MAPS_DETAILS.get('apiKey');
    }

    public static String getRootUrl() {
        initSettings();
        return GOOGLE_MAPS_DETAILS.get('rootUrl');
    }

    public static String getEndpoint(String endpoint) {
        return getRootUrl() + endpoint;
    }

}